FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY PersonalProductivityApp.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build -c Release -o app/build

FROM build AS publish
RUN dotnet publish -c Release -o app/publish

# figure out how to publish to nginx container
# FROM nginx:alpine AS final
# WORKDIR /usr/share/nginx/html
# COPY --from=publish /app/publish/ .
# COPY nginx.conf /etc/nginx/nginx.conf
